name: release-flow

# https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release
# on: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    runs-on: ${{ matrix.os.imageName }}
    strategy:
      matrix:
        rust_toolchain: ["stable"]
        os:
          - imageName: ubuntu-latest
          - imageName: "macOS-latest"
          - imageName: "windows-latest"

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          override: true
          profile: minimal
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v1
      - name: Make release-ci-flow
        run: cargo make release-ci-flow
        # env:
        #   DEVELOPER_DIR: "/Applications/Xcode_11.app/Contents/Developer"
      - name: Upload to gitHub release
        run: cargo make github-upload-flow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref }}
          # GITHUB_REPOSITORY: ${{ GITHUB_REPOSITORY }}
